# Generated by Django 2.0.2 on 2018-04-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
